CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	public_id VARCHAR(255) UNIQUE NOT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
